# Copyright 2010-2011 Sean Cribbs and Basho Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
source :rubygems

gem 'i18n'
gem 'builder'
gem 'rspec', "~>2.4.0"
gem 'fakeweb', ">=1.2"
gem 'rack', '>=1.0'
gem 'rake'
gem 'bundler'
gem 'excon', "~>0.6.1"
gem 'beefcake', '~>0.3.1'

platforms :mri do
  gem 'yajl-ruby'
end

platforms :jruby do
  gem 'json'
  gem 'jruby-openssl'
end

group :integration do
  gem 'activesupport', '~>3.0'
end
