# A sample Gemfile
source :gemcutter

gem 'i18n'

group 'spec' do
  gem 'builder'
end

gem 'rspec', "~>2.0.0"
gem 'fakeweb', ">=1.2"
gem 'rack', '>=1.0'
gem 'curb', '>=0.6'
gem 'yajl-ruby'
gem 'rake'
gem 'bundler'
