source :gemcutter

gem 'i18n'
gem 'builder'
gem 'rspec', "~>2.4.0"
gem 'fakeweb', ">=1.2"
gem 'rack', '>=1.0'
gem 'rake'
gem 'bundler'
gem 'excon', "~>0.3.4"
# Needs fix for repeated submessages, in the meantime use my fork
# (version 0.1.5)
gem 'beefcake', '~>0.1.5', :git => "git://github.com/seancribbs/beefcake.git"

if defined? JRUBY_VERSION
  gem 'json'
  gem 'jruby-openssl'
else
  gem 'curb', '>=0.6'
  gem 'yajl-ruby'
end

group :integration do
  gem 'activesupport', '~>3.0'
end
