require 'rubygems'
require 'rake/gempackagetask'

gemspec = Gem::Specification.new do |gem|
  gem.name = "riak-client"
  gem.summary = %Q{riak-client is a rich client for Riak, the distributed database by Basho.}
  gem.description = %Q{riak-client is a rich client for Riak, the distributed database by Basho. It supports the full HTTP interface including storage operations, bucket configuration, link-walking and map-reduce.}
  gem.version = File.read('../VERSION').strip
  gem.email = "sean@basho.com"
  gem.homepage = "http://seancribbs.github.com/ripple"
  gem.authors = ["Sean Cribbs"]
  gem.add_development_dependency "rspec", "~>2.4.0"
  gem.add_development_dependency "fakeweb", ">=1.2"
  gem.add_development_dependency "rack", ">=1.0"
  gem.add_development_dependency "curb", ">=0.6"
  gem.add_development_dependency "excon", "~>0.5.7"
  gem.add_dependency "i18n", ">=0.4.0"
  gem.add_dependency "builder", "~>2.1.2"
  gem.add_dependency "beefcake", "~>0.2.0"

  gem.files = %W{
                  erl_src/riak_kv_test_backend.beam
                  erl_src/riak_kv_test_backend.erl
                  Gemfile
                  lib/active_support/cache/riak_store.rb
                  lib/riak/bucket.rb
                  lib/riak/cache_store.rb
                  lib/riak/client/beefcake/messages.rb
                  lib/riak/client/beefcake/object_methods.rb
                  lib/riak/client/beefcake_protobuffs_backend.rb
                  lib/riak/client/curb_backend.rb
                  lib/riak/client/excon_backend.rb
                  lib/riak/client/http_backend/configuration.rb
                  lib/riak/client/http_backend/object_methods.rb
                  lib/riak/client/http_backend/request_headers.rb
                  lib/riak/client/http_backend/transport_methods.rb
                  lib/riak/client/http_backend.rb
                  lib/riak/client/net_http_backend.rb
                  lib/riak/client/protobuffs_backend.rb
                  lib/riak/client/pump.rb
                  lib/riak/client.rb
                  lib/riak/core_ext/blank.rb
                  lib/riak/core_ext/extract_options.rb
                  lib/riak/core_ext/slice.rb
                  lib/riak/core_ext/stringify_keys.rb
                  lib/riak/core_ext/symbolize_keys.rb
                  lib/riak/core_ext/to_param.rb
                  lib/riak/core_ext.rb
                  lib/riak/failed_request.rb
                  lib/riak/i18n.rb
                  lib/riak/invalid_response.rb
                  lib/riak/link.rb
                  lib/riak/locale
                  lib/riak/locale/en.yml
                  lib/riak/map_reduce/filter_builder.rb
                  lib/riak/map_reduce/phase.rb
                  lib/riak/map_reduce.rb
                  lib/riak/map_reduce_error.rb
                  lib/riak/robject.rb
                  lib/riak/search.rb
                  lib/riak/test_server.rb
                  lib/riak/util/escape.rb
                  lib/riak/util/fiber1.8.rb
                  lib/riak/util/headers.rb
                  lib/riak/util/multipart/stream_parser.rb
                  lib/riak/util/multipart.rb
                  lib/riak/util/tcp_socket_extensions.rb
                  lib/riak/util/translation.rb
                  lib/riak/walk_spec.rb
                  lib/riak.rb
                  Rakefile
                  riak-client.gemspec
                  spec/fixtures/cat.jpg
                  spec/fixtures/multipart-blank.txt
                  spec/fixtures/multipart-with-body.txt
                  spec/fixtures/server.cert.crt
                  spec/fixtures/server.cert.key
                  spec/fixtures/test.pem
                  spec/integration/riak/cache_store_spec.rb
                  spec/integration/riak/http_backends_spec.rb
                  spec/integration/riak/protobuffs_backends_spec.rb
                  spec/integration/riak/test_server_spec.rb
                  spec/riak/bucket_spec.rb
                  spec/riak/client_spec.rb
                  spec/riak/curb_backend_spec.rb
                  spec/riak/escape_spec.rb
                  spec/riak/excon_backend_spec.rb
                  spec/riak/headers_spec.rb
                  spec/riak/http_backend/configuration_spec.rb
                  spec/riak/http_backend/object_methods_spec.rb
                  spec/riak/http_backend/transport_methods_spec.rb
                  spec/riak/http_backend_spec.rb
                  spec/riak/link_spec.rb
                  spec/riak/map_reduce/filter_builder_spec.rb
                  spec/riak/map_reduce/phase_spec.rb
                  spec/riak/map_reduce_spec.rb
                  spec/riak/multipart_spec.rb
                  spec/riak/net_http_backend_spec.rb
                  spec/riak/robject_spec.rb
                  spec/riak/search_spec.rb
                  spec/riak/stream_parser_spec.rb
                  spec/riak/walk_spec_spec.rb
                  spec/spec_helper.rb
                  spec/support/drb_mock_server.rb
                  spec/support/http_backend_implementation_examples.rb
                  spec/support/mock_server.rb
                  spec/support/mocks.rb
                  spec/support/test_server.yml.example
                  spec/support/unified_backend_examples.rb
              }

  gem.test_files = gem.files.grep(/_spec\.rb$/)
end

# Gem packaging tasks
Rake::GemPackageTask.new(gemspec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

task :gem => :gemspec

desc %{Build the gemspec file.}
task :gemspec do
  gemspec.validate
  File.open("#{gemspec.name}.gemspec", 'w'){|f| f.write gemspec.to_ruby }
end

desc %{Release the gem to RubyGems.org}
task :release => :gem do
  system "gem push pkg/#{gemspec.name}-#{gemspec.version}.gem"
end

require 'rspec/core'
require 'rspec/core/rake_task'

desc "Run Unit Specs Only"
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = "spec/riak/**/*_spec.rb"
end

namespace :spec do
  desc "Run Integration Specs Only"
  RSpec::Core::RakeTask.new(:integration) do |spec|
    spec.pattern = "spec/integration/**/*_spec.rb"
  end

  desc "Run All Specs"
  RSpec::Core::RakeTask.new(:all) do |spec|
    spec.pattern = "spec/**/*_spec.rb"
  end
end

task :default => :spec
