require 'rubygems'
require 'rake/gempackagetask'

gemspec = Gem::Specification.new do |gem|
  gem.name = "riak-client"
  gem.summary = %Q{riak-client is a rich client for Riak, the distributed database by Basho.}
  gem.description = %Q{riak-client is a rich client for Riak, the distributed database by Basho. It supports the full HTTP interface including storage operations, bucket configuration, link-walking and map-reduce.}
  gem.version = File.read('../VERSION').strip
  gem.email = "seancribbs@gmail.com"
  gem.homepage = "http://seancribbs.github.com/ripple"
  gem.authors = ["Sean Cribbs"]
  gem.add_development_dependency "rspec", "~>2.0.0"
  gem.add_development_dependency "fakeweb", ">=1.2"
  gem.add_development_dependency "rack", ">=1.0"
  gem.add_development_dependency "curb", ">=0.6"
  gem.add_dependency "activesupport", ">= 2.3.5"
  gem.add_dependency "i18n", "~>0.4.0"
  gem.requirements << "`gem install curb` for better HTTP performance"

  files = FileList["**/*"]
  files.exclude /\.DS_Store/
  files.exclude /\#/
  files.exclude /~/
  files.exclude /\.swp/
  files.exclude '**/._*'
  files.exclude '**/*.orig'
  files.exclude '**/*.rej'
  files.exclude /^pkg/
  files.exclude 'riak-client.gemspec'
  files.exclude 'spec/support/test_server.yml'

  gem.files = files.to_a

  gem.test_files = FileList["spec/**/*.rb"].to_a
end

# Gem packaging tasks
Rake::GemPackageTask.new(gemspec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

task :gem => :gemspec

desc %{Build the gemspec file.}
task :gemspec do
  gemspec.validate
  File.open("#{gemspec.name}.gemspec", 'w'){|f| f.write gemspec.to_ruby }
end

desc %{Release the gem to RubyGems.org}
task :release => :gem do
  system "gem push pkg/#{gemspec.name}-#{gemspec.version}.gem"
end

require 'rspec/core'
require 'rspec/core/rake_task'

desc "Run Unit Specs Only"
Rspec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = "spec/riak/**/*_spec.rb"
end

namespace :spec do
  desc "Run Integration Specs Only"
  Rspec::Core::RakeTask.new(:integration) do |spec|
    spec.pattern = "spec/integration/**/*_spec.rb"
  end

  desc "Run All Specs"
  Rspec::Core::RakeTask.new(:all) do |spec|
    spec.pattern = "spec/**/*_spec.rb"
  end
end

task :default => :spec
