source :rubygems

gemspec
gem 'bundler'
gem 'riak-client', :path => "../riak-client"

platforms :mri_18, :jruby do
  gem 'ruby-debug'
end

platforms :mri_19 do
  gem 'ruby-debug19'
end

platforms :jruby do
  gem 'jruby-openssl'
end
