source "http://rubygems.org/"

gem 'bundler'
gem 'riak-client', :path => "../riak-client"
gem 'yajl-ruby'
gem 'curb', '>0.6'
gem 'activemodel', '3.0.0.rc'
gem 'rspec', '2.0.0.beta.18'
gem 'tzinfo'
gem 'rake'
