#!/usr/bin/env ruby

require 'yaml'

settings = {
  'temp_dir'  => './.riaktest',
  'bin_dir'   => ENV['RIAK_BIN_DIR'],
  :app_config => {
    :riak_search => {
      :enabled => false
    }
  }
}

settings_string = settings.to_yaml

projects = %w[ riak-client riak-sessions ripple ]

projects.each do |project|
  File.open("#{project}/spec/support/test_server.yml", 'w') do |f|
    f.write(settings_string)
  end
end

