#!/usr/bin/env ruby

require 'yaml'

settings = {
  'root'  => File.expand_path('.riaktest'),
  'source'   => ENV['RIAK_BIN_DIR'],
  :env => {
    :riak_kv => {
      :riak_kv_stat => false
    }
  }
}

settings_string = settings.to_yaml

projects = %w[ riak-client riak-sessions ripple ]

projects.each do |project|
  File.open("#{project}/spec/support/test_server.yml", 'w') do |f|
    f.write(settings_string)
  end
end

